### PR TITLE
Add prometheus metrics

### PR DESCRIPTION
**Pull request by edisonz0718**
Issue #84 

Final metric dashboard: 
Screen Shot 2023-04-30 at 10 59 53 PM

### CODE REVIEW

**Review by LeoHChen — COMMENTED** [review]
* please associate this PR with a github issue to describe the goals and steps of implementation.  I can see metrics is a big project and we will need a lot of follow up PRs.
* please include test results as comment to this PR.
* do you have a namespace set for all the metrics?

**Comment by edisonz0718** [comment]
> * please associate this PR with a github issue to describe the goals and steps of implementation.  I can see metrics is a big project and we will need a lot of follow up PRs.
> * please include test results as comment to this PR.
> * do you have a namespace set for all the metrics?

Updated the description and the associated issue.
For namespace, yes, the namespace is the application id.

**Comment by LeoHChen** [comment]
> Updated the description and the associated issue. For namespace, yes, the namespace is the application id.

Is the application id fixed?  What's the current application id you used?

**Comment by edisonz0718** [comment]
> > Updated the description and the associated issue. For namespace, yes, the namespace is the application id.
> 
> Is the application id fixed? What's the current application id you used?

It's defined in the config file. Right now it's called 'api'

**Comment by LeoHChen** [comment]
> > > Updated the description and the associated issue. For namespace, yes, the namespace is the application id.
> > 
> > 
> > Is the application id fixed? What's the current application id you used?
> 
> It's defined in the config file. Right now it's called 'api'
got it, better use a unique name later, like 'story_prod'.

**Review by LeoHChen — APPROVED** [review]

**Pull request merged**
